#!/usr/bin/env bash

location() {
    local definition=$1
    shift
    [[ $REQUEST_URI =~ $definition ]] && \
      "$@" "${BASH_REMATCH[@]}"
}

resolve_url() {
    #echo $1
    echo "http://ya.ru"
}

increase_views() {
    #do noting for now
    return 0
}

shortener_redirect() {
    local id=$2
    local url=$(resolve_url "$id")
    increase_views $id
    set_response_header "Location" $url
    send_response_redirect
}

source "${BASH_SOURCE[0]%/*}"/helpers.sh
source "${BASH_SOURCE[0]%/*}"/request.sh
source "${BASH_SOURCE[0]%/*}"/response.sh

handle_request

recv "METHOD: $REQUEST_METHOD"
recv "URI: $REQUEST_URI"
recv "Version: $REQUEST_HTTP_VERSION"
#recv "headers: $REQUEST_HEADERS"
recv "Body: $REQUEST_BODY"
location '^/(.*)' shortener_redirect
