#!/usr/bin/env bash

source "${BASH_SOURCE[0]%/*}"/helpers.sh
source "${BASH_SOURCE[0]%/*}"/request.sh
source "${BASH_SOURCE[0]%/*}"/response.sh
source "${BASH_SOURCE[0]%/*}"/shortener.sh

#Depends: bash, tr, sed, awk, lockfile, rev

location() {
    local definition=$1
    shift
    [[ $REQUEST_URI =~ $definition ]] && \
      "$@" "${BASH_REMATCH[@]}"
}

post() {
    [[ $REQUEST_METHOD == 'POST' ]] && location "$@"
}

get() {
    [[ $REQUEST_METHOD == 'GET' ]] && location "$@"
}

shortener_redirect() {
    local id=$2
    local url=$(resolve_url "$id")
    recv "Redirecting id: $id to $url"
    [ -n "$url" ] || \
        send_response_internal_error

    #increase_views $id
    set_response_header "Location" $url
    send_response_redirect
}

shorten_url() {
    local url=$(get_json_val "url" $REQUEST_BODY)
    [ -n "$url" ] || \
        send_response_bad_request
    recv "Shorten url: $url"

    local shortcode=$(do_locked shorten $url)
    local server_url=$(server_url)
    local newurl="://$server_url/$shortcode"
    send_json <<< "{\"url\":\"$newurl\"}"
}

handle_request

recv "METHOD: $REQUEST_METHOD"
recv "URI: $REQUEST_URI"
recv "Version: $REQUEST_HTTP_VERSION"
#recv "headers: $REQUEST_HEADERS"
recv "Body: $REQUEST_BODY"

post '^/(.*)' shorten_url
get '^/(.*)' shortener_redirect

send_response_not_found
